model:
  class_path: anomalib.models.Fastflow
  init_args:
    backbone: resnet18
    pre_trained: true
    flow_steps: 8
    hidden_ratio: 1.0

data:
  class_path: anomalib.data.Folder
  init_args:
    name: custom
    root: ./data/custom
    normal_dir: train/good
    abnormal_dir: test/defect
    train_batch_size: 32
    eval_batch_size: 1

trainer:
  accelerator: auto
  devices: 1
  max_epochs: 500
  default_root_dir: ./results
